import sqlite3
import os

def add_cover_images(db_path, book_isbn, image_path):
    # Connect to the SQLite database
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Read the image file
    with open(image_path, 'rb') as input_file:
        blob_data = input_file.read()

    # Update the Book table
    cursor.execute("UPDATE Book SET Cover = ? WHERE ISBN = ?", (sqlite3.Binary(blob_data), book_isbn))

    # Commit the changes and close the connection
    conn.commit()
    conn.close()

# Add Pictures to database
add_cover_images('library.db', 1, 'Pictures/TASSJM.jpg')
add_cover_images('library.db', 2, 'Pictures/TOGSJM.jpg')
add_cover_images('library.db', 3, 'Pictures/COMSJM.jpg')
add_cover_images('library.db', 4, 'Pictures/HOFSJM.jpg')
add_cover_images('library.db', 5, 'Pictures/QOSSJM.jpg')
add_cover_images('library.db', 6, 'Pictures/EOSSJM.jpg')
add_cover_images('library.db', 7, 'Pictures/TODSJM.jpg')
add_cover_images('library.db', 8, 'Pictures/KOASJM.jpg')
add_cover_images('library.db', 9, 'Pictures/CARAVAL.jpg')
add_cover_images('library.db', 10, 'Pictures/LEGENDARY.jpg')
add_cover_images('library.db', 11, 'Pictures/FINALE.jpg')
add_cover_images('library.db', 12, 'Pictures/SABLB.jpg')
add_cover_images('library.db', 13, 'Pictures/SASLB.jpg')
add_cover_images('library.db', 14, 'Pictures/RARLB.jpg')
add_cover_images('library.db', 15, 'Pictures/SOCLB.jpg')
add_cover_images('library.db', 16, 'Pictures/CKLB.jpg')
add_cover_images('library.db', 17, 'Pictures/KOSLB.jpg')
add_cover_images('library.db', 18, 'Pictures/ROWLB.jpg')
add_cover_images('library.db', 19, 'Pictures/TPWRF.jpg')
add_cover_images('library.db', 20, 'Pictures/TDRRFK.jpg')
add_cover_images('library.db', 21, 'Pictures/TBGRFK.jpg')
add_cover_images('library.db', 22, 'Pictures/TCPHB.jpg')
add_cover_images('library.db', 23, 'Pictures/TWKHB.jpg')
add_cover_images('library.db', 24, 'Pictures/QONHB.jpg')
add_cover_images('library.db', 25, 'Pictures/MSLY.jpg')
add_cover_images('library.db', 26, 'Pictures/TKQHH.jpg')
add_cover_images('library.db', 27, 'Pictures/TBTHH.jpg')
add_cover_images('library.db', 28, 'Pictures/THPHH.jpg')
add_cover_images('library.db', 29, 'Pictures/TDIJQ.jpg')
add_cover_images('library.db', 30, 'Pictures/TVWLMJQ.jpg')
add_cover_images('library.db', 31, 'Pictures/AOFAGJQ.jpg')
add_cover_images('library.db', 32, 'Pictures/RMBJQ.jpg')
add_cover_images('library.db', 33, 'Pictures/TSPWLJQ.jpg')
add_cover_images('library.db', 34, 'Pictures/WHWWJQ.jpg')
add_cover_images('library.db', 35, 'Pictures/IIHKJQ.jpg')
add_cover_images('library.db', 36, 'Pictures/OTWTTWJQ.jpg')
add_cover_images('library.db', 37, 'Pictures/TFEBS.jpg')
add_cover_images('library.db', 38, 'Pictures/TWOABS.jpg')
add_cover_images('library.db', 39, 'Pictures/THOABS.jpg')
add_cover_images('library.db', 40, 'Pictures/TWOKBS.jpg')
add_cover_images('library.db', 41, 'Pictures/WORBS.jpg')
add_cover_images('library.db', 42, 'Pictures/EDBS.jpg')
add_cover_images('library.db', 43, 'Pictures/OBBS.jpg')
add_cover_images('library.db', 44, 'Pictures/DSBS.jpg')
add_cover_images('library.db', 45, 'Pictures/ROWBS.jpg')
add_cover_images('library.db', 46, 'Pictures/TEOTWRB.jpg')
add_cover_images('library.db', 47, 'Pictures/TGHRJ.jpg')
add_cover_images('library.db', 48, 'Pictures/TDRRJ.jpg')
add_cover_images('library.db', 49, 'Pictures/TSRRJ.jpg')
add_cover_images('library.db', 50, 'Pictures/TFOHRJ.jpg')
add_cover_images('library.db', 51, 'Pictures/LOCRJ.jpg')
add_cover_images('library.db', 52, 'Pictures/ACOSRJ.jpg')
add_cover_images('library.db', 53, 'Pictures/TPODRJ.jpg')
add_cover_images('library.db', 54, 'Pictures/WHRJ.jpg')
add_cover_images('library.db', 55, 'Pictures/COTRJ.jpg')
add_cover_images('library.db', 56, 'Pictures/KODRJ.jpg')
add_cover_images('library.db', 57, 'Pictures/TGSRJ.jpg')
add_cover_images('library.db', 58, 'Pictures/TOMRJ.jpg')
add_cover_images('library.db', 59, 'Pictures/AMOLRJ.jpg')
add_cover_images('library.db', 60, 'Pictures/TFOTRJRRT.jpg')
add_cover_images('library.db', 61, 'Pictures/TTTJRRT.jpg')
add_cover_images('library.db', 62, 'Pictures/TROTKJRRT.jpg')
add_cover_images('library.db', 63, 'Pictures/RRPB.jpg')
add_cover_images('library.db', 64, 'Pictures/GSPB.jpg')
add_cover_images('library.db', 65, 'Pictures/MSPB.jpg')
add_cover_images('library.db', 66, 'Pictures/IGPB.jpg')
add_cover_images('library.db', 67, 'Pictures/DAPB.jpg')
add_cover_images('library.db', 68, 'Pictures/TSOAMM.jpg')
add_cover_images('library.db', 69, 'Pictures/CMM.jpg')